### ISSUE TITLE
RHEL 8.0?

### ISSUE THREAD

**Issue by dominiquearpin** [nexcess/puppet-auditd#7]
Seem /etc/audisp is remove from RHEL 8.0: https://access.redhat.com/solutions/3806561

Audit 3.0 replaces audispd with auditd in RHEL 8

**Comment by sedunne** [comment]
Hey there, I just replied to the PR but we're not looking to add RHEL/CentOS 8 support to the module. Thank you for the contribution though, and I'm sorry it took us so long to acknowledge this.
